org: juliabengt
service: quiztopiaapi
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  environment:
    USERS_TABLE: UsersTable
    QUIZ_TABLE: QuizTable2
    JWT_SECRET: minhemliganyckel

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:Query
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - dynamodb:GetItem
            - dynamodb:Scan
          Resource:
            - arn:aws:logs:eu-north-1:954976318596:log-group:/aws/lambda/quiztopiaapi-dev-login:*
            - arn:aws:logs:eu-north-1:954976318596:log-group:/aws/lambda/quiztopiaapi-dev-createAccount:*
            - arn:aws:dynamodb:eu-north-1:954976318596:table/${self:provider.environment.USERS_TABLE}
            - arn:aws:dynamodb:eu-north-1:954976318596:table/${self:provider.environment.USERS_TABLE}/index/UsernameIndex
            - arn:aws:dynamodb:eu-north-1:954976318596:table/${self:provider.environment.QUIZ_TABLE}

functions:
  createAccount:
    handler: src/createAccount/index.handler
    events:
      - http:
          path: /
          method: post
          cors: true

  login:
    handler: src/login/index.login
    events:
      - http:
          path: /login
          method: post
          cors: true

  createQuiz:
    handler: src/createQuiz/index.createQuiz
    events:
      - http:
          path: /quiz
          method: post
          cors: true

  getAllQuiz:
    handler: src/getAllQuiz/index.getAllQuiz
    events:
      - http:
          path: /getAllQuiz
          method: get
          cors: true

  getQuizById:
    handler: src/getQuizById/index.getQuizById
    events:
      - http:
          path: /getQuizById/{quizId}
          method: get
          cors: true

  deleteQuiz:
    handler: src/deleteQuiz/index.deleteQuiz
    events:
      - http:
          path: /deleteQuiz/{quizId}
          method: delete
          cors: true

  postQuestion:
    handler: src/addQuestion/index.postQuestion
    events:
      - http:
          path: /{quizId}/question
          method: post
          cors: true

resources:
  Resources:
    UsersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: 'userId'
            AttributeType: 'S'
          - AttributeName: 'username'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'userId'
            KeyType: 'HASH'
        GlobalSecondaryIndexes:
          - IndexName: 'UsernameIndex'
            KeySchema:
              - AttributeName: 'username'
                KeyType: 'HASH'
            Projection:
              ProjectionType: 'ALL'
        BillingMode: PAY_PER_REQUEST

    QuizTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        TableName: ${self:provider.environment.QUIZ_TABLE}
        AttributeDefinitions:
          - AttributeName: 'quizId'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'quizId'
            KeyType: 'HASH'
        BillingMode: PAY_PER_REQUEST
