# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: juliabengt
# "service" is the name of this project. This will also be added to your AWS resource names.
service: quiztopiaapi
frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1

functions:
  createAccount:
    handler: src/createAccount/index.handler
    events:
      - httpApi:
          path: /
          method: post
